apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: second
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: second
  replicas: 2 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: second
    spec:
      containers:
      - name: second
        image: gcr.io/symmetric-lock-357601/sec:latest
        ports:
        - containerPort: 82
        - containerPort: 443
